### ISSUE TITLE
Question: How to see more than "last 13 lines of output"

### ISSUE THREAD

**Issue by berndbischl** [craigcitro/r-travis#150]
I sometimes have the very annoying problem that some of my test only fail on travis. 

But then I only see "Last 13 lines of output", which is not even close of enough to help me. 

I know, this is more of an R CMD check question than a Travis one, but does one of you know a configuration / option workaround so I can see my fully unitest logs?

This drives me crazy and has eaten up too much of my time already....

**Comment by craigcitro** [comment]
hi @berndbischl,

one question first: are you using r-travis (this repo) or native R support in travis?

for this repo, you want to include a section like

    after_script:
     - ./travis-tool.sh dump_logs

and it'll `cat` all the logs produced by `R CMD check`. (you can also use `after_failure`, which is probably *more* appropriate, but either will work.)

for native travis integration, the fix is the same -- but that's actually a temporary workaround. the plan is to make all failures automatically print the logs, and the code is currently there -- there's just a bug with error handling and exit codes that i'm going to fix next chance i get.

**Comment by craigcitro** [comment]
and sorry for the painful debugging! :wink:

**Comment by berndbischl** [comment]
The yml is here:
https://github.com/berndbischl/mlr/blob/master/.travis.yml

And as you can see I already dump logs. The problem, like I said, is that this is probably(?) a misfortunate "feature" of R CMD check to only display the last 13 lines. So this can happen locally in exactly the same fashion - but there I can look at the logs.

Hang on, is this due to an exit code problem? I dump on after_failure, do I need to change this to after_script, as you say?

**Comment by craigcitro** [comment]
aha -- `on_failure` isn't a valid key. it should be `after_failure`.

http://lint.travis-ci.org/berndbischl/mlr

**Comment by berndbischl** [comment]
I am an idiot. And after_script is still the better option. And the URL is helpful.

Thanks for your help.

**Comment by krlmlr** [comment]
Related: hadley/testthat#201 (a reporter that limits itself to 13 lines for `R CMD check`). Probably this will work by default in the next CRAN release of `testthat`, should already work if you install it from GitHub.

**Comment by berndbischl** [comment]
Thanks for the heads up, this is good news.

Although I would have CRAN rather increase this arbitrary limit, but well.... better than nothing.
