### ISSUE TITLE
Handling older package dependencies

### ISSUE THREAD

**Issue by JEFworks** [craigcitro/r-travis#162]
Hi,

My R package requires an older version of a particular dependency. In my package DESCRIPTION, I require `Imports: RcppArmadillo (== 0.4.650.1.1)` 

In my `.travis.yml` I just use 
```
install:
  ## For installing all CRAN dependencies using DESCRIPTION
  - ./travis-tool.sh install_deps
```
to install my dependencies. 

My package has passed all R CMD check and R CMD BiocCheck but the travis testing is failing due to the following error `Package required and available but unsuitable version: ‘RcppArmadillo’`

From the travis log file, I can see that `RcppArmadillo` is being installed but the version isn't being taken into consideration.

Is there a way to have travis install particular versions of an R package instead of the latest?

Thanks for the help!

Best,
Jean

**Comment by craigcitro** [comment]
hi jean -- do you have a link to a failing build?

**Comment by JEFworks** [comment]
Here you go: https://travis-ci.org/hms-dbmi/scde/builds/74557923
Let me know if you need anything else. Thanks!

**Comment by JEFworks** [comment]
Thanks so much for the help, Craig!

Just FYI, I merged your pull but since my package has a few warnings associated, travis failed since you had set 'WARNINGS_ARE_ERRORS=1'. I tried changing to `WARNINGS_ARE_ERRORS=0` in [this build](https://github.com/hms-dbmi/scde/commit/0394ccc8a67ccb7f4b2e3ad1849af195d7a5bd2f) but still got the following error `Found warnings, treated as errors. Clear or unset the WARNINGS_ARE_ERRORS environment variable to ignore warnings.` I removed `WARNINGS_ARE_ERRORS` in [the latest build](https://github.com/hms-dbmi/scde/commit/399356f012b6157b97e88c113cc2e851daeae86c) and now the build is passing. I'm not sure if this is a bug, or if I needed to set to 0 in quotes. 

Thanks again!

**Comment by craigcitro** [comment]
i only added that because you'd had `warnings_are_errors: true` in the file when I started. 

The code will treat warnings as errors if that variable is present at all; the right way to skip it is to drop that line, which it sounds like you hit on. ;)

also, i forgot to mention: there's also the option of switching to `language: r`, which would simplify your config a little more. however, given that you're not using latex, it'll just slow down your builds a bit (since you'd be installing latex every time). if you end up wanting to start building manuals, lemme know and i'll help you switch over.
